module.exports = Object.freeze({
  emailIsRequired: 'Email is required!',
  emailIsInvalid: 'Email is invalid!',
  emailConfirmationTokenNotFound: 'Email confirmation token is invalid!',
  emailAlreadyExist: 'Email already exists!',
  emailNotFound: 'Email not found!',
  userNotFound: 'User not found!',
  nameIsInvalid: 'Name is invalid!',
  userErrorOcurred: 'An error occurred while finding the user!',
  passwordIsRequired: 'Password is required!',
  firstNameIsRequired: 'First name is required!',
  lastNameIsRequired: 'Last name is required!',
  confirmPasswordIsRequired: 'Confirm password field is required!',
  weakPassword: 'Password must be at least 6 characters and max 30 characters',
  passwordNoMatch: 'Passwords must match',
  passwordIncorrect: 'Password incorrect!',
  noTokenProvided: 'No token provided.',
  tokenFailAuth: 'Failed to authenticate token.',
  codeIsInvalid: 'Code is invalid.',
  notificationTitleisInvalid: 'Notification is invalid',
  notificationsType: 'Notifications in invalid',
});
