export const ACCESSORIES_EXPANDABLE_ITEMS = [
  'Trepavice',
  'Pribor',
  'Šiljila',
  'Nokti',
  'Kistovi',
  'Torbe',
  'Setovi',
  'Pincete',
  'Kosa',
  'Blenderi',
  'Dom',
  'Maske za lice',
  'Kozmetičke kutije',
];
